// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbi7bFjl4cNO0vyRMlYoECsTl3GI0XfBE',
    appId: '1:937036593332:web:fef68e52eacb23a91d3fe1',
    messagingSenderId: '937036593332',
    projectId: 'location-and-chat',
    authDomain: 'location-and-chat.firebaseapp.com',
    storageBucket: 'location-and-chat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA2k2DcBhD3Sgxmf5S-LLr66E3p9GIDNo',
    appId: '1:937036593332:android:04e5fefc437789171d3fe1',
    messagingSenderId: '937036593332',
    projectId: 'location-and-chat',
    storageBucket: 'location-and-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIxici2fsuka-g5AchmYA8pj_aR7gpYNY',
    appId: '1:937036593332:ios:17ca82568a5f212d1d3fe1',
    messagingSenderId: '937036593332',
    projectId: 'location-and-chat',
    storageBucket: 'location-and-chat.appspot.com',
    iosClientId: '937036593332-aj5d3cpn3vtab8a5mh19kjf9su7pbldd.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasePractice',
  );
}
